In [1]:
import pandas as pd
from pathlib import Path

raw = Path("../data_raw/mock_prices.csv")
out = Path("../data_clean/clean_housing.csv")

df = pd.read_csv(raw)

# Params (simple assumptions for now)
ASSUMED_FLAT_SIZE_M2 = 70
ASSUMED_MORTGAGE_RATE = 0.05  # 5% annual carrying-cost proxy

# Derived indicators
df["price_to_income_ratio"] = (df["price_per_m2"] * ASSUMED_FLAT_SIZE_M2) / (df["avg_monthly_wage"] * 12)
df["rent_vs_buy_index"] = (df["avg_monthly_rent"] * 12) / (df["price_per_m2"] * ASSUMED_FLAT_SIZE_M2 * ASSUMED_MORTGAGE_RATE)

out.parent.mkdir(parents=True, exist_ok=True)
df.to_csv(out, index=False)
print(" Saved", out)
df.head()

 Saved ../data_clean/clean_housing.csv

,latvia,year,region,price_per_m2,avg_monthly_wage,avg_monthly_rent,price_to_income_ratio,rent_vs_buy_index
0,LV,2023,Riga,2100,1500,700,8.166667,1.142857
1,LV,2023,Pieriga,1800,1500,650,7.000000,1.238095
2,LV,2023,Liepaja,1350,1300,450,6.057692,1.142857
3,LV,2024,Riga,2270,1600,740,8.276042,1.117684
4,LV,2024,Pieriga,1900,1600,680,6.927083,1.227068